// Code generated by "stringer -type Type"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Symbol-0]
	_ = x[Number-1]
	_ = x[List-2]
	_ = x[Proc-3]
	_ = x[Lambda-4]
}

const _Type_name = "SymbolNumberListProcLambda"

var _Type_index = [...]uint8{0, 6, 12, 16, 20, 26}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
