// Code generated by "stringer -type TokenType"; DO NOT EDIT.

package lexer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenEOF-0]
	_ = x[TokenOpenParen-1]
	_ = x[TokenCloseParen-2]
	_ = x[TokenIllegal-3]
	_ = x[TokenAtom-4]
	_ = x[TokenBoolean-5]
	_ = x[TokenNumber-6]
	_ = x[TokenIdentifier-7]
	_ = x[TokenDot-8]
	_ = x[TokenChar-9]
	_ = x[TokenQuote-10]
	_ = x[TokenDQuote-11]
	_ = x[TokenBQuote-12]
	_ = x[TokenComma-13]
	_ = x[TokenNewline-14]
}

const _TokenType_name = "TokenEOFTokenOpenParenTokenCloseParenTokenIllegalTokenAtomTokenBooleanTokenNumberTokenIdentifierTokenDotTokenCharTokenQuoteTokenDQuoteTokenBQuoteTokenCommaTokenNewline"

var _TokenType_index = [...]uint8{0, 8, 22, 37, 49, 58, 70, 81, 96, 104, 113, 123, 134, 145, 155, 167}

func (i TokenType) String() string {
	if i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
